Use `[SecureContext]` instead of manually throwing an exception
w3c-cg/web-nfc pull request #143
Opened 2018-04-02 15:58 UTC by romandev

2018-04-03 10:33 UTC, kenchris commented
@alexshalamov are you fine with this? I assume this is the same you do in generic sensors?

2018-04-03 14:05 UTC, alexshalamov requested changes

2018-04-03 14:05 UTC, alexshalamov commented on index.html
> +  <p class="note">
I'm not sure whether this extra information adds something, localhost considered to be secure.

2018-04-03 14:05 UTC, alexshalamov commented on index.html
> -            If any exception occurs while running these steps, reject
This block is not related to secure context, we can keep it as it is.

2018-04-03 14:05 UTC, alexshalamov commented on index.html
> -            If any exception occurs while running these steps, reject
Same as above, let's remove custom handling of secure context and remove only following blocks:

```
-          <li>
-            If the <a>incumbent settings object</a> is not a
-            <a>secure context</a>, reject <var>promise</var> with
-            <code>"<a>SecurityError</a>"</code> and abort these steps.
-            <div class="note">
-              Browsers may ignore this rule for development purposes only.
-            </div>
-          </li>
```

2018-04-03 16:31 UTC, romandev commented
@alexshalamov Thank you for review. I addressed your comments.

2018-04-03 16:34 UTC, jyasskin approved these changes

2018-04-04 06:46 UTC, alexshalamov approved these changes

2018-04-04 06:49 UTC, alexshalamov commented
@romandev Thanks!

2018-04-04 06:50 UTC, merged